create or replace noneditionable package ut_template
is


    ----------------------------------------------------------------------------
    -- FBUT Framework
    -- Package : UT_TEMPLATE
    -- Version : 1.0.0
    --
    -- Source template generator
    ----------------------------------------------------------------------------



    ----------------------------------------------------------------------------
    -- Package specification
    ----------------------------------------------------------------------------

    function package_spec_header
    (
        p_test_package_name varchar2
    )
    return clob;



    ----------------------------------------------------------------------------
    -- Package body
    ----------------------------------------------------------------------------

    function package_body_header
    (
        p_test_package_name varchar2
    )
    return clob;



    ----------------------------------------------------------------------------
    -- Test method name
    ----------------------------------------------------------------------------

    function test_method_name
    (
        p_method_name varchar2
    )
    return varchar2;



    ----------------------------------------------------------------------------
    -- Setup / teardown
    ----------------------------------------------------------------------------

    function setup_block
    return clob;



    function teardown_block
    return clob;



    ----------------------------------------------------------------------------
    -- Procedure test skeleton
    ----------------------------------------------------------------------------

    function procedure_test_template
    (
        p_method_name varchar2
    )
    return clob;



    ----------------------------------------------------------------------------
    -- Function test skeleton
    ----------------------------------------------------------------------------

    function function_test_template
    (
        p_method_name varchar2,
        p_return_type varchar2
    )
    return clob;



end ut_template;
/
create or replace noneditionable package body ut_template
is


    ----------------------------------------------------------------------------
    -- Version
    ----------------------------------------------------------------------------

    g_version constant varchar2(20) := '1.0.0';



    ----------------------------------------------------------------------------
    -- Package spec header
    ----------------------------------------------------------------------------

    function package_spec_header
    (
        p_test_package_name varchar2
    )
    return clob
    is

        l_source clob;


    begin


        ut_builder.clear;



        ut_builder.add_comment
        (
            'Generated by FBUT Framework'
        );



        ut_builder.add_comment
        (
            'Package: '
            ||
            p_test_package_name
        );



        ut_builder.new_line;



        ut_builder.append_line
        (
            'create or replace package '
            ||
            upper(p_test_package_name)
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.new_line;



        ut_builder.append_line
        (
            'end '
            ||
            upper(p_test_package_name)
            ||
            ';'
        );



        ut_builder.append_line
        (
            '/'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end package_spec_header;






    ----------------------------------------------------------------------------
    -- Package body header
    ----------------------------------------------------------------------------

    function package_body_header
    (
        p_test_package_name varchar2
    )
    return clob
    is

        l_source clob;


    begin



        ut_builder.clear;



        ut_builder.add_comment
        (
            'Generated by FBUT Framework'
        );



        ut_builder.append_line
        (
            'create or replace package body '
            ||
            upper(p_test_package_name)
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.new_line;



        ut_builder.append_line
        (
            'end '
            ||
            upper(p_test_package_name)
            ||
            ';'
        );



        ut_builder.append_line
        (
            '/'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end package_body_header;







    ----------------------------------------------------------------------------
    -- Test method name
    ----------------------------------------------------------------------------

    function test_method_name
    (
        p_method_name varchar2
    )
    return varchar2
    is
    begin


        return
            'test_'
            ||
            lower(p_method_name);



    end test_method_name;







    ----------------------------------------------------------------------------
    -- Setup
    ----------------------------------------------------------------------------

    function setup_block
    return clob
    is

        l_source clob;


    begin



        ut_builder.clear;



        ut_builder.append_line
        (
            'procedure setup'
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.append_line
        (
            'begin'
        );



        ut_builder.indent;



        ut_builder.append_line
        (
            'null;'
        );



        ut_builder.outdent;



        ut_builder.append_line
        (
            'end setup;'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end setup_block;







    ----------------------------------------------------------------------------
    -- Teardown
    ----------------------------------------------------------------------------

    function teardown_block
    return clob
    is

        l_source clob;


    begin



        ut_builder.clear;



        ut_builder.append_line
        (
            'procedure teardown'
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.append_line
        (
            'begin'
        );



        ut_builder.indent;



        ut_builder.append_line
        (
            'null;'
        );



        ut_builder.outdent;



        ut_builder.append_line
        (
            'end teardown;'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end teardown_block;







    ----------------------------------------------------------------------------
    -- Procedure template
    ----------------------------------------------------------------------------

    function procedure_test_template
    (
        p_method_name varchar2
    )
    return clob
    is

        l_source clob;


    begin



        ut_builder.clear;



        ut_builder.append_line
        (
            'procedure '
            ||
            test_method_name(p_method_name)
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.append_line
        (
            'begin'
        );



        ut_builder.indent;



        ut_builder.append_line
        (
            'null;'
        );



        ut_builder.outdent;



        ut_builder.append_line
        (
            'end '
            ||
            test_method_name(p_method_name)
            ||
            ';'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end procedure_test_template;








    ----------------------------------------------------------------------------
    -- Function template
    ----------------------------------------------------------------------------

    function function_test_template
    (
        p_method_name varchar2,

        p_return_type varchar2
    )
    return clob
    is

        l_source clob;


    begin



        ut_builder.clear;



        ut_builder.append_line
        (
            'procedure '
            ||
            test_method_name(p_method_name)
        );



        ut_builder.append_line
        (
            'is'
        );



        ut_builder.append_line
        (
            'l_result '
            ||
            p_return_type
            ||
            ';'
        );



        ut_builder.append_line
        (
            'begin'
        );



        ut_builder.indent;



        ut_builder.append_line
        (
            'null;'
        );



        ut_builder.outdent;



        ut_builder.append_line
        (
            'end '
            ||
            test_method_name(p_method_name)
            ||
            ';'
        );



        l_source :=
            ut_builder.get_clob;



        return l_source;



    end function_test_template;




end ut_template;
/
